# Generated by Django 3.2.5 on 2021-08-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('event_month', models.CharField(max_length=20)),
                ('event_date', models.DateTimeField()),
                ('event_organizer', models.CharField(max_length=15)),
                ('event_venue', models.CharField(max_length=16)),
                ('event_duration', models.TimeField()),
                ('event_goal', models.CharField(max_length=200)),
                ('event_approved_by', models.CharField(max_length=20)),
            ],
        ),
    ]
