# Generated by Django 3.2.5 on 2021-08-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='event_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='event_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='event_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='event_name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
