# Generated by Django 3.2.5 on 2021-08-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('course_code', models.IntegerField()),
                ('course_syllabus', models.FileField(blank=True, null=True, upload_to='images/')),
                ('course_trainer', models.CharField(max_length=30)),
                ('course_duration', models.CharField(max_length=30)),
                ('course_projects', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
