# Generated by Django 3.2.5 on 2021-08-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_projects',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
