# Generated by Django 3.2.5 on 2021-08-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('bank_account', models.IntegerField()),
                ('nationality', models.CharField(max_length=14)),
                ('phone_Number', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=15)),
                ('county', models.CharField(max_length=12)),
                ('contract', models.FileField(upload_to='')),
                ('id_number', models.IntegerField()),
                ('cv', models.FileField(upload_to='')),
                ('proffession', models.CharField(max_length=32)),
                ('salary', models.PositiveBigIntegerField()),
            ],
        ),
    ]
