# Generated by Django 3.2.5 on 2021-08-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
