# Generated by Django 3.2.5 on 2021-08-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(help_text='e.g Jane', max_length=10),
        ),
    ]
