# Generated by Django 3.2.5 on 2021-08-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='county',
        ),
        migrations.RemoveField(
            model_name='student',
            name='regions',
        ),
    ]
